/* Certificate header file */

#define OT_CLI_BBTC_X509_CERT \
    "-----BEGIN CERTIFICATE-----\r\n" \
    "MIIBezCCASKgAwIBAgIEAQIDBDAKBggqhkjOPQQDAjBaMQswCQYDVQQGEwJERTER\r\n" \
    "MA8GA1UEBxMIR2FyY2hpbmcxDDAKBgNVBAsTA1NUQTERMA8GA1UEChMITXlWZW5k\r\n" \
    "b3IxFzAVBgNVBAMTDm9wdG90cm9uaWMuY29tMB4XDTIzMDgwODEwNDI0OVoXDTI0\r\n" \
    "MDgwODEwNDI0OVowGjEYMBYGA1UEAxMPVW5saW1pdGVkQWNjZXNzMFkwEwYHKoZI\r\n" \
    "zj0CAQYIKoZIzj0DAQcDQgAED3i3op7pdhAk8QvpytITPSrnhsFVg6SZhbFbAmw9\r\n" \
    "fCTGOomXDYARz2h3lSHxVdZUKjsn2bDX3s0PJ4urbpZhLqMWMBQwEgYJKwYBBAGC\r\n" \
    "3yoDBAUAAQEBATAKBggqhkjOPQQDAgNHADBEAiAyCjOy0NDw00w7tNq0HK0LX2rk\r\n" \
    "bRcWg8L4mHdYS5+lRwIgRM4b1eItMNpFTSLq174ZIjtq96QSEHA/8yS1UPyo9MM=\r\n" \
    "-----END CERTIFICATE-----\r\n"

#define OT_CLI_BBTC_PRIV_KEY \
    "-----BEGIN EC PRIVATE KEY-----\r\n" \
    "MHcCAQEEIHqCO3YjGKu1469GTKwS+w+1MHCMwKPtN+yreiXbn0b5oAoGCCqGSM49\r\n" \
    "AwEHoUQDQgAED3i3op7pdhAk8QvpytITPSrnhsFVg6SZhbFbAmw9fCTGOomXDYAR\r\n" \
    "z2h3lSHxVdZUKjsn2bDX3s0PJ4urbpZhLg==\r\n" \
    "-----END EC PRIVATE KEY-----\r\n"

#define OT_CLI_BBTC_TRUSTED_ROOT_CERTIFICATE \
    "-----BEGIN CERTIFICATE-----\r\n" \
    "MIIB3TCCAYOgAwIBAgIJAIEkU9Kpk7sQMAoGCCqGSM49BAMCMFoxCzAJBgNVBAYT\r\n" \
    "AkRFMREwDwYDVQQHEwhHYXJjaGluZzEMMAoGA1UECxMDU1RBMREwDwYDVQQKEwhN\r\n" \
    "eVZlbmRvcjEXMBUGA1UEAxMOb3B0b3Ryb25pYy5jb20wHhcNMjMwMzI0MjMwODI2\r\n" \
    "WhcNMjYwMzI0MjMwODI2WjBaMQswCQYDVQQGEwJERTERMA8GA1UEBxMIR2FyY2hp\r\n" \
    "bmcxDDAKBgNVBAsTA1NUQTERMA8GA1UEChMITXlWZW5kb3IxFzAVBgNVBAMTDm9w\r\n" \
    "dG90cm9uaWMuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEIZXjlDNlAxIV\r\n" \
    "k19EVfeQRj755MWWlZnDhaZKbMPuuP+EML9zdIwWDeCleRP5tKq5fmWp0s81lRjr\r\n" \
    "F2AwIs/TLaMyMDAwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUDf0KHNxzEy7q\r\n" \
    "znA405Fx1lQsRLowCgYIKoZIzj0EAwIDSAAwRQIhAPDKNTxO8sLkns1y7ec2w2oR\r\n" \
    "CYoQyDj2d498XeWYkSVuAiBz+GSRnTmdCFzQKfL8/ma7QaNdXihKYrWUdqvlynVV\r\n" \
    "MQ==\r\n" \
    "-----END CERTIFICATE-----\r\n"
